name: weather_service
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/snitch24/weather_service.git
# publish_to: none
environment:
  sdk: '>=2.18.0-271.4.beta <3.0.0'

dependencies:
  path: ^1.8.0
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
